export type modalState =
  | "post"
  | "post-delete"
  | "post-comment"
  | "story"
  | "story-delete"
  | "profile-picture"
  | "followers"
  | "following"
  | "users"
  | "logout"
  | "login"
  | "not-supported"
  | "unfollow"
  | "none";
